id = "flexographic-theme"
name = "Flexographic"
version = "0.0.1"
schema_version = 1
authors = ["Guilherme Sarria"]
description = "Warm light and dark themes for Zed."
repository = "https://github.com/guisarria/flexographic-theme"
